language: rust

matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode11.5
    - os: osx
      osx_image: xcode10.1

script:
  - cargo check --verbose
  - cargo test
